#!/bin/bash
## Tag handling script

function print_help {
  echo "This script handles git release tags."
  echo "Create tag:"
  echo -e "\t$(basename $0) tag_name"
  echo "Move tag to latest commit:"
  echo -e "\t$(basename $0) -u/--update tag_name"
  echo "Rename tag:"
  echo -e "\t$(basename $0) -r /--rename old_tag_name new_tag_name"
  echo ""
  echo "Delete tag:"
  echo -e "\t$(basename $0) -d/--delete tag_name"
  echo ""
}

update_tag="false"
rename_tag="false"
delete_tag="false"
tag_name="$1"

while getopts "hu:r:d:-:" opt; do
  case ${opt} in
    h)
      print_help
      exit 0
      ;;
    u)
      update_tag="true"
      tag_name="${OPTARG}"
      ;;
    r)
      rename_tag="true"
      old_tag="${OPTARG}"
      new_tag="${!OPTIND}"
      OPTIND=$(( $OPTIND + 1 ))
      ;;
    d)
      delete_tag="true"
      tag_name="${OPTARG}"
      ;;
    -) # long options
      case ${OPTARG} in
        update)
          update_tag="true"
          tag_name="${!OPTIND}"
          OPTIND=$(( $OPTIND + 1 ))
          ;;
        delete)
          delete_tag="true"
          tag_name="${!OPTIND}"
          OPTIND=$(( $OPTIND + 1 ))
          ;;
        rename)
          rename_tag="true"
          old_tag="${!OPTIND}"
          OPTIND=$(( $OPTIND + 1 ))
          new_tag="${!OPTIND}"
          OPTIND=$(( $OPTIND + 1 ))
          ;;
        help)
          print_help
          exit 0
          ;;
        *)
          echo "Bad option \"--${OPTARG}\""
          exit 1
          ;;
      esac
      ;;
  esac
done

if [ -z "$1" ]; then
  git tag
else
  if [ "${update_tag}" == "true" ]; then
    git tag | grep ${tag_name} &> /dev/null
    modify_old_tags="true"
    if [ "$?" -eq 0 ]; then
      git tag --force ${tag_name}
    else
      git tag ${tag_name}
      modify_old_tags="false"
    fi
  elif [ "${rename_tag}" == "true" ]; then
    git tag ${new_tag} ${old_tag}
    git tag -d ${old_tag}
    modify_old_tags="true"
  elif [ "${delete_tag}" == "true" ]; then
    git tag -d ${tag_name}
    modify_old_tags="true"
  else
    git tag ${tag_name}
    modify_old_tags="false"
  fi

  if [ "$?" -eq 0 ]; then
    read -p "Update tags in origin? (Y/n) " ans
    while [ "$resp" != "given" ]; do
      if [[ $ans =~ ^([yY][eE][sS]|[yY])$ ]] || [ -z "$ans" ]; then
        ans="y"
        resp="given"
      elif [[ $ans =~ ^([nN][oO]|[nN])$ ]]; then
        ans="n"
        resp="given"
        exit 0
      else
        read -p "Type y or n: " ans
      fi
    done

    if [ "${modify_old_tags}" == "true" ]; then
      if [ "${delete_tag}" == "true" -o "${update_tag}" == "true" ]; then
        tag_to_remove="${tag_name}"
      elif [ "${rename_tag}" == "true" ]; then
        tag_to_remove="${old_tag}"
      fi

      if ! git push --delete origin "${tag_to_remove}"; then
        echo "Error while deleting '${tag_to_remove}' from origin."
        echo "Try again manually via"
        echo "  git push --delete origin '${tag_to_remove}'"
        echo ""
        exit 1
      fi
    fi
    if ! git push --tags; then
      echo "Error while pushing tags."
      echo "Try again manually via"
      echo "  git push --tags"
      echo ""
      exit 1
    fi
  else
    exit $?
  fi
fi
